#!/usr/bin/python3

from PyQt5.QtWidgets import QApplication, QMainWindow, QFileDialog, QTableView, QHeaderView
import sys

from lib.TableModel import TableModel
from lib.Filter import Filter
from lib.menubar import menubar

class faultViewer(QMainWindow):
    def __init__(self):
        super().__init__()
        
        menubar(self)

        self.view = QTableView(self)
        self.setCentralWidget(self.view)

        self.model = False
        self.hide = False

        if len(sys.argv) == 2:
            self.open(sys.argv[1])

        self.show()

    def open(self, f = None):
        if not f:
            path = QFileDialog.getOpenFileName(self)[0]
        else:
            path = f

        if path:
            self.model = TableModel(path)
            self.view.setModel(self.model)
            self.view.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeToContents)
            self.view.horizontalHeader().setStretchLastSection(True)
            self.view.verticalHeader().setSectionResizeMode(QHeaderView.Fixed)
            self.view.verticalHeader().setDefaultSectionSize(15)
            self.view.setShowGrid(False)

        self.hideButton.setEnabled(True)
        self.highlightButton.setEnabled(True)
        self.checkButton.setEnabled(True)
        self.fix100Button.setEnabled(True)

    def save(self):
        if self.model:
            self.model.save()

    def export(self, f = None):
        if self.model:
            if not f:
                path = QFileDialog.getSaveFileName(self)[0]
            else:
                path = f
            if path:
                self.model.export(path)

    def hideToggle(self):
        self.hide = not self.hide
        if self.hide:
            self.filter = Filter(self)
            self.filter.setSourceModel(self.model)
            self.view.setModel(self.filter)
        else:
            self.view.setModel(self.model)

    def highlightToggle(self):
        self.model.highlightToggle()

    def checkToggle(self):
        self.model.checkToggle()

    def fix100Toggle(self):
        self.model.fix100Toggle()

if __name__ == '__main__':
    app = QApplication(sys.argv)
    masterView = faultViewer()
    sys.exit(app.exec_())
